const actionTypes = {
    STACK_OVERFLOW_GET_DATA: 'STACK_OVERFLOW_GET_DATA',
    STACK_OVERFLOW_REQUEST: 'STACK_OVERFLOW_REQUEST',
    STACK_OVERFLOW_FAIL: 'STACK_OVERFLOW_FAIL'
};

export default actionTypes